GunGonGamLee/ft_transcendence

- .gitignore
- requirements.txt
- src/settings.py
- .env 파일 수정 (slack 캔버스에 저장해두고 모두 수정했다면 알려줄 것)
- setting.py DATABASE / .env파일 연결하는 코드 추가
- requirements.txt에 psycopg2, django-environ 추가
> chore: postgresql rds 연결

- .gitignore
- docker-compose.yml
- elk/elasticsearch/Dockerfile
- elk/elasticsearch/config/elasticsearch.yml
- elk/kibana/Dockerfile
- elk/kibana/config/kibana.yml
- elk/logstash/Dockerfile
- elk/logstash/conf/logstash.yml
- elk/logstash/pipeline/logstash.conf
- volumes/elasticsearch/config/elasticsearch.yml
SSL 인증서 발급을 통한 https로 ELK 스택 연동하기 완료
> chore: kibana 연동 완료 및 SSL 인증서 발급 

- backend/login/urls.py
- backend/src/settings.py
- backend/src/urls.py
> feat: swagger base url 수정

- backend/api/urls.py
- backend/src/urls.py
- `src/urls.py`에서 1차적으로 `/api`로 오는 요청은 `api/urls.py`로 라우트하도록 했습니다.
- `api/urls.py`에서는 요청에 해당하는 각각의 앱으로 라우트하도록 했습니다.
> feat: 백엔드 api prefix api로 수정

- Dockerfile
- docker-compose.yml
- nginx/config/nginx.conf
index.html nginx.conf로 마운트 후 첫 페이지 띄우기 성공
역사적인 가상화
> feat: index.html 을 nginx conf 내부로 마운트

- .idea/.gitignore
- .idea/modules.xml
- .idea/transcendence.iml
- .idea/vcs.xml
- frontend/src/app.js
- frontend/src/constants/routeInfo.js
- frontend/src/pages/chooseGameMode/page.js
- frontend/src/pages/main/page.js
- frontend/src/pages/makeNickname/page.js
- frontend/src/pages/notfound.js
- frontend/src/router.js
- frontend/src/utils/querySelector.js
> style: jsdoc 추가 했습니다

- backend/pingpong/models.py
- backend/users/models.py
- 테이블 명 및 `models.ForeignKey()` 필드의 이름 각각 `class Meta`와 `db_column`에 명시
- erdcloud와 동기화
- 외래 키의 경우, `[참조하려는 테이블]_id`로 컬럼명 통일
- `..._date`는 `.._at`으로 통일
- `profile` -> `avatar`로 컬럼명 변경
- 테이블 이름 `FriendList`에서 `Friend`로 변경
- 친구 신청 상태를 나타내는 `status` 컬럼 추가
- 사용자 지정 게임에 두 가지 모드를 선택할 수 있음에 따라 CustomGame 모델 수정
- 이제 이 테이블에서 플레이어 정보(`player1_id` 등)를 다루지 않음
- 게임 모드(2인용, 토너먼트)를 나타내는 `mode(int)` 컬럼 추가
- `content_object` 컬럼을 `GenericForeignKey`로 설정하여 `Tournament` 또는 `TwoPlayerGame`의 데이터를 받아올 수 있게 함
- 사용자 지정 방을 나타내는 모델 추가
- 비밀번호(`password`) 추가
- 설명(`description`) 제거
- erdcloud와 동기화
> feat: DB 수정

- backend/login/urls.py
- backend/login/views.py
- backend/requirements.txt
42로그인 구현 완료.
코드 리팩토링으로 구글 로그인과 42로그인의 겹친 기능들을 합쳐놨습니당
> feat: 42 login 구현했습니다 #71

- .gitignore
> docs: edit .gitignore

- docker-compose.yml
- frontend/src/constants/routeInfo.js
- frontend/src/header/mainHeader/header.js
- frontend/src/pages/game-mode/gameModeUnit.js
- frontend/src/pages/game-mode/page.js
게임모드 페이지 구현했습니다.
main-header에서 뒤로가기 키 누르면 뒤로가게 했습니다.
> feat: game mode 페이지 구현

- backend/login/serializers.py
- backend/login/urls.py
- backend/login/views.py
- backend/src/exceptions.py
로그인 후 이메일 인증 코드 관련 처리까지 모두 끝냈습니다.
#89
> feat: 로그인 기능 구현 완료 #89

- backend/src/settings.py
- docker-compose.yml
- nginx/config/nginx.conf
* hashicorp vault 를 django production 모드에서 비밀을 가져올 수 있게 수정
> feat: hashicorp vault DEBUG마다 분기 nginx.conf 수정

- backend/requirements.txt
- backend/src/settings.py
> fix: CORS header 긴급수정

- backend/requirements.txt
> docs: requirements 파일 수정

- backend/login/views.py
> fix: 리다이렉션 uri 수정

- backend/login/views.py
> fix: swagger response status 추가

- backend/login/views.py
> fix: user model 수정

- backend/login/views.py
- frontend/src/pages/auth/page.js
- frontend/src/pages/register/page.js
> fix: 로그인 해결!!!!!!!

- backend/users/models.py
> fix: superuser 메소드 삭제

- frontend/src/pages/histories/custom-page.js
- frontend/src/pages/histories/page.js
- frontend/src/pages/histories/summary-page.js
- `useState()`, `setState()` 추가
- `setState()`의 불필요한 async 제거
- 컨테이너를 나타내는 변수의 경우, `$`를 변수명의 접두사로 사용
- 렌더링하는 함수의 반환 값으로 백틱으로 정의한 element 사용
> refactor: 사용자 지정 모드 전적 페이지 리팩토링

- frontend/src/pages/register/page.js
- frontend/src/router.js
닉네임 생성 부분 ajax로직 추가했습니다
register 페이지 내부에서 fetch하는 부분 3개 있는데 3개 request 유사해서 request option 뱉는 함수 하나 추가했습니다.
> feat: 닉네임 fetch 로직 구현

- backend/api/urls.py
- backend/login/views.py
- backend/src/utils.py
- backend/users/urls.py
- backend/users/views.py
> Feat: nickname 설정 API 구현 #127

- frontend/src/pages/login/page.js
- frontend/src/pages/register/page.js
루트페이지에서 이미 jwt토큰을 가지고 있는 경우 /api/users/me로 fetch 보내서 game-mode로 navigate되게 했습니다.
> feat:  루트페이지에서 이미 jwt토큰 있는지가입 완료한 친구이지 검사하는 로직 추가

- backend/users/serializers.py
- backend/users/urls.py
- backend/users/views.py
> feat: /users/me API 구현 #136

- backend/api/urls.py
- backend/friends/admin.py
- backend/friends/apps.py
- backend/friends/models.py
- backend/friends/serializers.py
- backend/friends/tests.py
- backend/friends/urls.py
- backend/friends/views.py
- backend/src/settings.py
> feat:  친구 추가 제거 삭제 안 쓰는 함수, exception 지우기

- frontend/src/pages/game-mode/page.js
- frontend/src/pages/register/page.js
- frontend/src/utils/useState.js
1. useState 오류 수정 했습니다.
``` js
if (typeof stateInput === "object") {
let state = [...stateInput];
const getState = () => {
return state;
};
const setState = (newState) => {
state = [...newState];
component[render](); // 그냥 render를 인자로 받으면 최신화가 안되버리는..!
};
return [getState, setState];
```
기존 코드에서는 array와 object전부 같은 분기로 들어가서 배열로 구조분해할당 되었습니다.
이를 아래와 같이 각 자료형에 맞게 처리해 주었습니다.
``` js
if (Array.isArray(stateInput)) {
// 배열일 경우
let state = [...stateInput];
const getState = () => {
return state;
};
const setState = (newState) => {
state = [...newState];
component[render](); // render 메서드 호출
};
return [getState, setState];
} else if (typeof stateInput === "object") {
// 객체일 경우 (단, null과 배열 제외)
let state = { …
```
> refactor: usestate 사용해서 이전 페이지들 리팩토링

- backend/src/settings.py
- docker-compose.yml
- elk/elasticsearch/config/elasticsearch.yml
- elk/kibana/config/kibana.yml
- elk/logstash/conf/logstash.yml
- elk/logstash/pipeline/logstash.conf
- nginx/config/modsecurity.conf
- nginx/config/nginx.conf
1. nginx log가 logstash에 연동되어 json-line 형태로 파싱되어 전달됩니다.
2. elk stack log level을 ERROR mode만 저장하도록 영구적으로 수정했습니다.
3. 볼륨 마운트를 아이맥으로 마운트되도록 수정했습니다.
4. modsecurity의 DEBUG 레벨을 없애서 로그를 최적화 시켰습니다.
> feat: nginx log를 logstash로 받아오기, elk stack log level 조정

- backend/users/views.py
> Feat: 닉네임 수정 api #173

- Dockerfile
- backend/requirements.txt
- docker-compose.yml
1. 보안이 향상되었습니다.
2. 이제 백엔드 서버는 WAS로 작동합니다
> feat: 이제 runserver 안 씀, container image는 python-slim

- backend/friends/models.py
- backend/games/models.py
- backend/games/serializers.py
- backend/src/choices.py
- backend/users/models.py
> Feat: 코드 리팩토링

- Dockerfile
- backend/friends/views.py
- backend/src/settings.py
- docker-compose.yml
- init.sh
- nginx/config/nginx.conf
nginx에서 정적파일 서빙 가능하도록 수정
딩디리딩딩딩
> feat: nginx에서 정적파일을 서빙할 수 있게 수정, 친구 삭제 기능 추가, localhost/admin 가능

- backend/games/views.py
- backend/src/choices.py
> Fix: 입장 버그 수정 

- backend/games/models.py
> Feat: GameRecordView model 생성

- frontend/assets/css/customGameList.css
- frontend/src/pages/custom-game-list/game-room-list.js
- frontend/src/pages/custom-game-list/page.js
- frontend/src/pages/custom-game-list/password-modal.js
- frontend/src/pages/custom-game-list/room-create-modal.js
- css 로 방 목록마다 네온효과 구현
- 방 걸러보기로 모드 filter-modal 구현
- 방 만들기 modal 구현
- 암호입력 modal 구현
- 네온 hover 구현 …
> feat : 사용자 지정 게임 목록 페이지 event기능 구현

- backend/requirements.txt
- backend/src/asgi.py
- backend/src/settings.py
- init.sh
- nginx/config/nginx.conf
> Feat: 소켓 연결 성공

- frontend/src/utils/useEffect.js
useEffect 구현
https://donghyk2.tistory.com/146 <-  구현 설명
``` javascript
let useEffect멈추는함수 = useEffect(콜백함수(), 감시 할 HTMLElement);
```
이렇게 사용합니다. useState와 달리 HTMLElement에 콜백함수 바인딩하는 함수이므로, 꼭 해당 엘리먼트가 렌더링 된 이후에 사용하세요!
> feat: useEffect 구현

- backend/src/asgi.py
- backend/src/jwt_authentication.py
- backend/src/settings.py
- nginx/config/nginx.conf
> Feat: socket jwt 토큰 검증 기능 추가

- frontend/index.html
- frontend/src/pages/game-mode/page.js
원래 bootstrap이 npm사용시 연결 링크로 되어 있어 cdn으로 변경했습니다.
game-mode 페이지에서 제대로 ui뜨는거 확인 가능합니다.
> fix: bootstrap cdn으로 바꿔줌

- backend/games/consumers.py
- backend/games/routing.py
- backend/src/asgi.py
> Feat: 게임방 입장 #168

- frontend/src/pages/custom-game-list/page.js
- frontend/src/pages/login/page.js
> refactor : 205 refactor 함수명 리팩토링

- Dockerfile
- Makefile
- backend/requirements.txt
- backend/src/settings.py
- docker-compose.yml
- init.sh
- nginx/Dockerfile
- nginx/config/nginx.conf
mkcert 인증서 발급 및 iMAC 환경에서 trust 하도록 설정 / daphne는 해결 못함
> build : hashicorpvault 비활성화 / nginx modsecurity 비활성화 / Makefile 추가

- frontend/src/header/mainHeader/header.js
무엇을 합니다!
- `useState` 사용
- `historiesHeader`에서 `MainHeader`로 변경
- 불필요한 `this` 키워드 제거
- 리팩토링
closes: #185 
- 로그인 후 헤더 불러오기
- 아바타 변경 시, `<img>` 태그의 `src`의 변경을 감지하여 `useReducer`를 사용하고 싶었으나, 이미지 태그에는 변화를 감지하는 어트리뷰트가 없음
> refactor: 메인 헤더 리팩토링

- backend/games/consumers.py
> hotfix: 입장 소켓 버그 수정 

- frontend/assets/css/game-mode.css
- frontend/src/pages/game-mode/gameModeUnit.js
- frontend/src/pages/game-mode/page.js
- game-mode 페이지에 대기 큐 모달 ui 구현 했습니다.
closes: #228
https://github.com/GunGonGamLee/ft_transcendence/assets/81581828/8c7b0814-a7ca-4835-ab06-2bc54278dc56
> feat: game-mode 페이지 스피너 ui 구현

- .gitignore
- backend/friends/consumers.py
- frontend/index.html
- frontend/src/header/mainHeader/header.js
- VSCODE 오류로 인해 git이 conflict 문제 났던 것 해결 후 올림
- JS 헤더 렌더링 시 로그인 소켓에 연결 보내도록
> hotfix: 실시간 친구 접속 깃 문제 hotfix

- backend/login/views.py
return을 했는데 finally가 실행이 되는게 말이 되냐
> fix: 로그인 버그 해결

- frontend/assets/css/errorPage.css
- frontend/assets/css/register.css
- frontend/src/header/mainHeader/header.js
- frontend/src/pages/game-mode/page.js
- frontend/src/pages/in-game/page.js
- frontend/src/pages/in-game/scoreBar.js
- frontend/src/pages/waiting-room/userUnit.js
- frontend/src/router.js
무엇을 합니다!
- 제가 만든 페이지 css 반응형으로 변경했습니다.
- router 로직 변경했습니다.
- router에서 해당 컴포넌트 instanceof 검사로직을 전에 제거해서 다시 올립니다.
closes: #238 
> fix: router 로직 추가, 만든 페이지 반응형으로 변경

- backend/friends/views.py
- backend/games/views.py
- backend/login/views.py
- backend/src/exceptions.py
- backend/users/views.py
> refactor: 예외처리 리팩토링

- backend/friends/consumers.py
- backend/login/urls.py
- backend/login/views.py
1. logout API 호출 시 모든 연결 소켓 끊어짐 
2.  백엔드에서 jwt token (cookie) 지우기 기능 설정완료
> feat: logout API / 실시간 연결 끊김 DB에 반영되는 기능 작성 완료

- backend/friends/views.py
- backend/login/views.py
- Friend Status에서 정의되지 않았던 ACCEPTED, REJECTED, PENDING을 수정 (이거 누가 바꿨지?)
- status 휴먼에러 수정
- DELETE 요청 BODY에 nickname을 담아서 보내주세요
> feat: 친구 신청 API 수정완료

- frontend/assets/css/common/header.css
- frontend/src/header/mainHeader/header.js
- frontend/src/utils/cookie.js
무엇을 합니다!
- 부트스트랩으로 사용자 정보(닉네임, 아바타) 부분 드롭 다운 리스트 적용
- 드롭 다운 리스트에서 전적으로 보러 갈지, 로그아웃 할지 선택
- 백엔드 로그아웃 API 적용
closes: #247
- 로컬 테스트
https://github.com/GunGonGamLee/ft_transcendence/assets/50291995/a2d70117-dec1-4f5a-928a-b09b233faf20
> feat: 로그아웃 API 적용

- backend/games/serializers.py
- backend/games/urls.py
- backend/games/views.py
- backend/src/settings.py
> feat: 사용자 게임 전적 API 구현 #261

- backend/src/settings.py
- frontend/assets/css/common/header.css
- frontend/src/header/mainHeader/header.js
무엇을 합니다!
- 헤더 내 아바타에 `max-height` 추가
- 백엔드에서 누락된 import 추가
- 아바타를 사용자가 업로드했을 때, 아바타의 크기가 header를 벗어나지 않게 하기 위함
closes: #270 
- 스웨거에서 아바타 파일 업로드 후 헤더 렌더링
> feat: 헤더 내 아바타 UI 수정

- frontend/src/pages/game-mode/page.js
- frontend/src/pages/in-game/page.js
- frontend/src/pages/in-game/scoreBar.js
공, 바 이미지태그에 canvas 적용했습니다.
- 기존 코드의 경우 useState를 사용할 계획이였습니다. 하지만 디바이스의 framerate마다 dom조작을 하게 되면 부하가 많이 걸린다는 가르침을 받고 canvas로 수정했습니다. 
- game-time state로 만들고 setInterval로 재렌더링 되게 했습니다.
- DOM 요소 조작: CSS를 변경하여 게임 요소를 이동시키는 방식은 실제로 DOM 요소의 속성을 조작합니다. 이 방식은 주로 HTML 요소를 직접적으로 이동, 크기 조정, 색 변경 등을 통해 시각적 변화를 주게 됩니다.
- 성능: 많은 DOM 조작은 브라우저의 리플로우(reflow)와 리페인트(repaint)를 유발하여 성능에 부담을 줄 수 있습니다. 특히 복잡한 애니메이션 또는 많은 요소가 동시에 움직이는 경우, 성능 저하가 발생할 수 있습니다.
- 접근성과 SEO: HTML 기반으로 …
> feat: in game canvas 사용해보기

- backend/games/models.py
- backend/games/serializers.py
- backend/games/views.py
- backend/src/pagination_utils.py
> feat: 게임방 목록 api #250

- backend/games/serializers.py
- backend/users/serializers.py
> fix: avatar 수정 #281

- backend/games/consumers.py
> feat: consumer group_send로 수정

- frontend/assets/css/friendsInfoModal.css
- frontend/src/header/mainHeader/friends-info-modal.js
- frontend/src/header/mainHeader/header.js
무엇을 합니다!
- 친구창 모달 렌더링 위치 조정
- 라우터를 해서 다른 페이지로 이동하면 계속 들고다녀야 할 친구창 모달이 날아가는 문제점을 발견하였고
이를 방지하고자 친구창 모달을 header에 렌더링하는 리팩토링 작업을 했습니다.
closes: #274
- header로 위치를 변경해도 제대로 렌더링 되는지 확인 
렌더링하는 위치를 변경했기 때문에 css에 변동이 생겼을 수 있으니 한번씩들 만져보시며 확인해주세요!
> refactor : 친구창 모달 렌더링 위치 변경

- frontend/src/pages/game-mode/page.js
- frontend/src/pages/in-game/page.js
- frontend/src/pages/login/page.js
- frontend/src/pages/register/page.js
- frontend/src/router.js
- frontend/src/utils/navigate.js
무엇을 합니다!
- game-mode 페이지에서 토너먼트 유닛 click시 ws 연결, onmessage, ws.close 추가했습니다.
- navigate시 두번째 인자로 object를 담아서 보낼 수 있게 변경했습니다.
- navigate, router에 두번째 인자 관련 로직 추가했습니다.
- 기존 errorpage로 이동 시 navigate 두 번째 인자로 number를 보냈는데 이를 object로 감싸줬습니다.
- 아직 완성 안된 페이지들에서 navigate 시 정보를 넘길 필요가 있습니다. 필요 없이 fetch하는 부분을 줄이기 위해서 변경했습니다.
closes: #279
> feat: game-mode ws연결, navigate 로직 변경

- frontend/assets/css/customGameList.css
- frontend/src/pages/custom-game-list/page.js
무엇을 합니다!
- 아이콘 크지 조정
- hover이벤트 다시 동작하도록 수정
- <a>태그를 사용하면 밑줄이 쳐져서 <div>태그로 변경
closes: #283
- docker환경에서 확인
또 스타일의 문제가 있다면 말씀해주세요!
> fix: 사용자 지정 게임 목록 css, 이벤트 에러 고치기

- frontend/src/header/mainHeader/header.js
무엇을 합니다!
- Response의 `avatar_file_name` 대신 `avatar` 사용
- 백엔드 API Response 변경
closes: #287 
- 로컬 e2e
> feat: avatar_file_name 대신 avatar 사용

- backend/games/consumers.py
> Feat: 게임방 퇴장 #183

- backend/games/consumers.py
> Feat: 비밀번호 검증 구현

- backend/games/models.py
- backend/games/tests.py
무엇을 합니다!
- 게임 관련 클래스 모델링
- 게임 클래스 함수 구현
- 게임 모듈 로직 구현
closes: #248 
- test_set_ball
- test_set_ball_direction_fail
- test_set_racket_position
- test_hit_racket
- test_hit_wall
- test_hit_nothing
- test_move_ball
- test_bounce
- test_is_goal_in
- test_update_score
- test_ball_reset
- 공의 속도는 3fp씩 늘어나게 했습니다. 이건 추후 화면 보고 조정하면 될 것 같습니다.
> feat: 게임 모듈 로직 구현

- backend/friends/urls.py
- backend/friends/views.py
- 친구창 유저 찾기 기능이 추가되었어요
- 친구 요청한 사용자 목록 API가 완성되었어요.
> feat: 친구창 유저 찾기 API, 친구 요청한 사용자 목록 API 완성

- backend/games/serializers.py
- backend/games/views.py
- backend/src/choices.py
- backend/src/exceptions.py
> fix: 버그 수정, 코드 리팩토링

- backend/games/views.py
> fix: 응답 빼먹은 거 수정

- backend/friends/consumers.py
- backend/friends/views.py
- backend/src/settings.py
- 친구 기능 소켓으로 분리 완료
- delete 기능 에러 메세지 제대로 찍히도록 수정
> feat: 친구 기능을 소켓으로 분리해보자

- frontend/src/pages/custom-game-list/page.js
- frontend/src/pages/custom-game-list/password-modal.js
- frontend/src/pages/custom-game-list/room-create-modal.js
- frontend/src/pages/waiting-room/userBox.js
- frontend/src/pages/waiting-room/userUnit.js
- frontend/src/router.js
custom-game-room 완성했습니다.
- custom-game-room api 이식 및 테스트 완료
- 이제 enterRoom에서 소켓을 만들어 waitingroom에다가 렌더링 정보와 함께 넘겨줍니다.
- 이것저것 테스트 해주세요
closes: #306
https://github.com/GunGonGamLee/ft_transcendence/assets/81581828/71345a99-1294-444b-9cb2-66f98f05cf74
> feat: custom game room완성!

- backend/friends/consumers.py
- backend/friends/views.py
- docker-compose.yml
- nginx/Dockerfile
- nginx/config/modsecurity.conf
- consumers.py 의 오타를 수정했습니다 (cancle - > cancel)
- views.py 의 오타를 수정했습니다. (messages->message)
- modsecurity의 방화벽이 이제 올라갑니다.
-
> fix: modsecurity 방화벽 모드 ON / Dockerfile 정리 및 오타 수정

- frontend/src/pages/custom-game-list/page.js
- frontend/src/pages/waiting-room/page.js
- frontend/src/pages/waiting-room/userBox.js
- frontend/src/pages/waiting-room/userUnit.js
waiting-room 완성했습니다.
closes: #320
https://github.com/GunGonGamLee/ft_transcendence/assets/81581828/a572f34d-1806-441b-ae78-bd90d0b570e4
> feat: waiting room에 usestate 소켓 이식

- docker-compose.yml
- frontend/src/global.js
- frontend/src/header/mainHeader/header.js
- frontend/src/pages/custom-game-list/page.js
- frontend/src/pages/game-mode/page.js
- init.sh
- 볼륨 path들을 보기 쉽게 수정
- init.sh에 환경변수 추가
-  웹소켓과 API가 나누어지게 프론트엔드 코드 수정
> build : 볼륨 path들 예쁘게 수정함 / init.sh에 환경변수 추가함 / 웹소켓과 API가 나누어지게

- frontend/src/header/mainHeader/header.js
- frontend/src/pages/custom-game-list/page.js
- frontend/src/pages/game-mode/page.js
- nginx/config/nginx.conf
- prod backend / Websocket URL을 나눴지만 연결 요청에서 /ws를 지우지 않아 발생하는 문제를 수정하였습니다.
- nginx.conf에서 표준 출력으로 너무 많은 로그를 찍어내던 문제를 수정했습니다.
> hotfix: /ws 경로 다시 제대로 가도록 수정함

- backend/games/consumers.py
- backend/games/views.py
> Feat: 비밀번호 해싱 #311

- frontend/src/header/mainHeader/header.js
무엇을 합니다!
-  url변수를 올바른 경로로 다시 지정
- 친구 추가, 수락, 삭제 이벤트 이후 스피너 갱신
- 친구 추가, 삭제시 다시 웹소켓으로 부터 데이터를 받아오기 전까지 갱신되지 않는 UI를 변경할 필요성이 있었음
closes: #336
- 친구 수락
- 친구 거절
- 친구 삭제
테스트 해보시고 문제있다면 알려주세요~!
>  feat : 친구모달창 스피너 삽입

- frontend/src/header/mainHeader/header.js
- frontend/src/pages/errorPage.js
- frontend/src/pages/waiting-room/countdownModal.js
- frontend/src/pages/waiting-room/page.js
무엇을 합니다!
- socket error 전용 errorcode 받는 errorpage 추가
- 게임 시작 버튼 누르면 카운트다운 모달 창 뜨고 게임 시작send보내게 변경
- 이러한 이유 때문에 변경했습니다!
closes: #341
> feat: waiting room 카운트다운 모달 로직 구현 , mainheader onclose 로직 추가

- backend/games/consumers.py
- backend/games/views.py
> Fix: 입장 버그 수정

- backend/friends/consumers.py
- frontend/src/global.js
- frontend/src/header/mainHeader/header.js
- frontend/src/router.js
- global.js conflict 사항 수정하여 다시 제대로 분기되도록
- 중복 로그인 consumer 처리하기
> feat: 로그인 중복을 막아보자

- backend/src/settings.py
- elk/logstash/pipeline/logstash.conf
- nginx/config/nginx.conf
- 조금 더 유의미한 log를 받아 파싱할 수 있도록 configuration 파일들을 수정했습니다.
> feat: nginx django에서 유의미한 로그 수집하여 json line으로 파싱

- frontend/src/pages/game-mode/page.js
- frontend/src/pages/tournament/page.js
- frontend/src/pages/waiting-room/page.js
무엇을 합니다!
- game-mode queue, waiting-room에서 소켓메시지로 받은 url로 소켓 연결하고 그 소켓의 메시지로 받은 match정보까지 같이 가지고 tournament페이지로 이동하게 변경
closes: #358
> feat: waiting-room, game-mode queue에서 소켓 로직 수정

- frontend/src/pages/custom-game-list/page.js
무엇을 합니다!
- 스피너 예쁘게 바꿨습니다.
https://github.com/GunGonGamLee/ft_transcendence/assets/81581828/bc3fd57a-37fe-4f86-8625-2481a719d989
closes: #362
> chore: spinner 옙브게 변경

- backend/games/consumers.py
- backend/games/models.py
- backend/games/urls.py
- backend/games/views.py
> fix: 게임 컨슈머 수정

- Dockerfile
- backend/src/settings.py
- docker-compose.yml
- elk/kibana/config/kibana.yml
- elk/logstash/conf/logstash.yml
- elk/logstash/pipeline/logstash.conf
- nginx/config/nginx.conf
1. Nginx : 우리 프로젝트의 요청을 반환하는 평균 레이턴시는 몇 ms일까요?
2. django : 사용자는 어떤 유형의 게임을 가장 선호할까요?
> feat: KIBANA에서 로그 수집할 거 정함 / Django, python 잘 받음

- docker-compose.yml
- elk/logstash/pipeline/logstash.conf
- kibana 입력 받는 사항 수정 
- grok 파싱하는 방법 수정하기
- 로그 뭐 받을지 확실하게 정해둠
> feat: kibana 끝

- backend/games/consumers/GameRoomConsumer.py
> fix: 퇴장 버그 수정

- frontend/src/constants/routeInfo.js
- frontend/src/pages/online-game/page.js
- frontend/src/pages/online-game/scoreBar.js
- frontend/src/pages/online-game/toast.js
- frontend/src/pages/waiting-room/page.js
- online-game 페이지 추가 후 socketmessage 보내는 키 이벤트 받기
- waiting-room 방장 아니면 game-start 버튼 안보이게 하기 
- online-game에서 새로고침/브라우저 종료가 일어났을때 websocket 연결끊게 추가했습니다. (브라우저가 자동으로끊어주는건 5초정도걸림)
closes: #377
> feat: waiting-room 방 다 차야 게임 시작 가능하게 변경, online-game 페이지 추가

- frontend/src/constants/routeInfo.js
- frontend/src/pages/match-up/page.js
- frontend/src/pages/online-game/page.js
- matchup 페이지에서 렌더링 정보 / 소켓 navigate에 담아서 online-game으로 이동
- arrow up down key event 추가
closes: #386
> feat: match up 페이지에서 online game 페이지로 소켓 전달

- backend/games/consumers/GameConsumer.py
> feat: 키보드 입력

- frontend/assets/css/localMatchUp.css
- frontend/src/constants/routeInfo.js
- frontend/src/pages/game-mode/page.js
- frontend/src/pages/in-game/page.js
- frontend/src/pages/local-match-up/page.js
- frontend/src/pages/local-match-up/playerNameInput.js
local-match-up 페이지 개발했습니다.
in-game 페이지로 navigate 시 인자로
``` js
info = {
curMatch: 1,
match: {
player1: "123",
player2: "123",
player3: "123",
player4: "123",
finalPlayer1: null,
finalPlayer2: null
}
}
```
이렇게 넘깁니다.
in-game 페이지에 TODO리스트로 작성해 두었습니다
https://github.com/GunGonGamLee/ft_transcendence/assets/81581828/aa773346-154f-4a1a-82f4-f0d40de1f572
closes: #389
> feat: local match up 페이지 개발

- backend/users/tests.py
- backend/users/views.py
무엇을 합니다!
- 아바타 기존 5개 중 한 개로 변경하는 API 구현
- API 추가
closes: #365 
- unit test
> feat: 아바타 변경 API 구현

- frontend/assets/css/histories.css
- frontend/src/constants/routeInfo.js
- frontend/src/pages/histories/page.js
- frontend/src/pages/histories/summary-page.js
무엇을 합니다!
- 백엔드 유저 전적 검색 API 이식
- 검색한 유저가 없을 경우 안내 메시지 출력
- 빈 문자열 입력 시, 본인 전적 검색
- 백엔드 유저 전적 검색 API 이식
closes: #383 
- e2e
https://github.com/GunGonGamLee/ft_transcendence/assets/50291995/ff2cf271-8bf7-4dc8-ae54-94bbcdfd98a5
> feat: 전적 페이지에서 유저 검색 api 이식

- frontend/src/pages/avatar/page.js
무엇을 합니다!
- 아바타 업데이트 API 이식
- 아바타 변경 페이지 누락된 jsdoc 추가
- 아바타 업데이트 API 이식
closes: #381 
- e2e
https://github.com/GunGonGamLee/ft_transcendence/assets/50291995/855f2009-0764-4de3-a2a4-b7cf472e0033
- 아바타 변경에 성공하면(`response.status_code === 200`) 헤더를 재렌더링하게 할 생각이었으나, 그럴 경우 웹소켓 연결에 문제가 생길 것 같아 헤더의 아바타 `<img>`의 src 어트리뷰트만 값을 변경했습니다.
> feat: 아바타 업데이트 API 이식

- frontend/assets/css/friendsInfoModal.css
- frontend/assets/css/histories.css
무엇을 합니다!
- 전적 페이지의 footer `z-index: 0` 로 조정
- 친구 모달 창 `z-index: 1` 로 조정
- 친구 모달 창위에 전적 페이지의 footer가 렌더링 됨
closes: #338 
- e2e
> feat: 전적 페이지 footer와 친구 모달 창의 z-index 조정

- frontend/src/pages/in-game/page.js
- frontend/src/pages/local-match-up/page.js
- frontend/src/pages/match-up/page.js
- frontend/src/pages/online-game/page.js
- frontend/src/router.js
- frontend/src/utils/deepCopy.js
- frontend/src/utils/useReducer.js
- 로컬게임에서 시작 시 fetch쏘게 추가
- online 게임에서 canvas socket 메시지 기반으로 draw하게 함
- local-game page 로직 완성
- deepCopy 함수로 따로 뺌
- router에서 info prevInfo 비교하는 부분 init에서도 추가  해줌(pathname같을때 route 안하는 이슈 있었음)
closes: #399
> feat: 로컬 게임 완성 / 온라인 게임 canvas 소켓메시지 기반으로 render / router info 관련 이슈 해결

- frontend/src/constants/routeInfo.js
- frontend/src/pages/histories/one-on-one-page.js
- frontend/src/pages/histories/tournament-page.js
무엇을 합니다!
- 전적 목록 페이지를 렌더링하는 함수에서 `$container`를 인자로 받아옴
- 라우터에서 전적 목록 페이지를 렌더링하는 함수 `.bind()` 사용 시, `.bind()`의 인자 변경
- 버그 Fix
closes: #392 
- e2e
https://github.com/GunGonGamLee/ft_transcendence/assets/50291995/c8056122-aec2-4023-b32a-373f325e5cd2
> fix: 전적 목록 페이지 새로고침 시 빈 화면

- backend/login/views.py
- 구글 로그인 URI와 인트라 42 URI를 분기하여 구글 로그인 시는 무조건 localhost, 42 INTRA login 시에는 BASE_URL을 기준으로 이메일 인증을 할 수 있도록 수정하였습니다.
> feat: 구글 로그인 URI / 인트라 42 URI 수정함

- backend/games/consumers/GameConsumer.py
> feat: pvp, pvp 도중 퇴장 구현 #312

- frontend/src/pages/local-game/page.js
- frontend/src/pages/match-up/page.js
- frontend/src/pages/online-game/page.js
> chore: info를 받는 페이지 새로고침 처리 / online-game에서 game-end 처리

- Dockerfile
- backend/src/settings.py
- backend/src/urls.py
- docker-compose.yml
무엇을 합니다!
1. 백엔드 컨테이너에 프론트엔드 아바타 폴더 볼륨 연결
2. `.init.sh` 파일 실행 위치 변경
3. `.env` 파일 백엔드 컨테이너 내부로 복사
1. redoc의 경우, `DEBUG = False`여도 동작하게 함
1. `ENV_PATH` 값 수정
- 백엔드의 `settings.py`에 `MEDIA_ROOT`를 프론트엔드 폴더 경로로 지정
- 따라서 파일이 저장되는 위치는 `/frontend/assets/images/avatar/`여야 함
- 백엔드 컨테이너에서 아바타 파일을 저장하는 함수가 실행되는데, 기존에는 백엔드 컨테이너 내부에 파일을 저장할 경로인 `/frontend/assets/images/avatar/`에 해당하는 디렉토리가 없어 파일이 저장되지 않음
- `static_volume`이 비어있어서 실질적으로 `/usr/share/nginx/html/static`은 빈 폴더
- 따라서 `backend/static`을 /usr/share/nginx/html/static`에 마운트
- 백엔드 컨테이너가 준비가 되면 실행하는데, `init.sh` 실행 시의 WORKDIR은 `/backend`였지만 `init.sh`는 컨테이너의 루트에 위치
- 컨테이너의 루트에서 실행해보려 했으나, 백엔드 모듈을 찾지 못함
- 따라서 `init.sh`을 컨테이너의 루트가 아닌 `/backend`의 하위에 COPY 후 실행
5. `.env` …
> feat: docker에서 redoc 사용 가능하게 함

- backend/games/consumers/GameConsumer.py
- backend/games/models.py
- backend/src/choices.py
> fix: 리팩토링 #312

- backend/games/consumers/GameConsumer.py
- backend/games/consumers/GameRoomConsumer.py
> fix: fix game status bug #425

- frontend/src/pages/custom-game-list/page.js
- frontend/src/pages/match-up/page.js
- frontend/src/pages/online-game/page.js
- frontend/src/pages/waiting-room/page.js
- frontend/src/utils/clickEvent.js
- waiting-room 게임 시작 시 기존 소켓 바로 닫게 변경
- 인게임 key 무한입력 막기(서버부하)
- clickOnce 함수 추가
- onlinegame에서 아직 경기 남은 사람들 match로 정보 가지고 이동시켜줌
- onlinegame 에서 history로 패자 / 결승전 통과자들 보내줌
- match1 match2 별로 game-end 메시지 두개 오는거 처리 
closes: #421
> fix: online-game waiting-room bug fix

- backend/games/serializers.py
> fix: winner 참조 500 에러 #429

- backend/games/consumers/GameConsumer.py
> feat: game match 정보 추가 #428

- backend/games/consumers/GameConsumer.py
- backend/games/consumers/GameRoomConsumer.py
> hotfix: 짜잘한 버그

- backend/games/consumers/GameConsumer.py
> feat: winner info update #419

- frontend/src/pages/match-up/page.js
- frontend/src/pages/online-game/page.js
- frontend/src/pages/waiting-room/page.js
- waiting-room start버튼 조건 오류 고쳐줌
- online-game 소켓 메시지 처리
- match-up 주석 추가
- 이러한 이유 때문에 변경했습니다!
closes: #440 
> fix: online game 소켓메시지 처리 해결

- backend/games/tests.py
무엇을 합니다!
- PingPongGame 초기화 시, player1, player2 전달
- ball.reset 호출 시, PingPongMap만 전달
- `PingPongGame` 구조 변경
- `ball.reset()` 인자 변경
closes: #402 
- unit test
> test(games): PingPongGame 모델 구조 변경에 따른 test 최신화

- backend/games/consumers/GameConsumer.py
- backend/games/serializers.py
제대로 작동 할랑가 모르겠습니다
테스트를 할 수가 없슴
> feat: 결승전 구현 #427

- backend/games/consumers/GameRoomConsumer.py
> fix: 게임 시작 시간 저장 #430

- backend/requirements.txt
- backend/src/settings.py
- backend/src/urls.py
- docker-compose.yml
- grafana/Dockerfile
- nginx/Dockerfile
- prometheus/Dockerfile
- Prometheus 도입
- node_exporter 도입 / 아이맥의 리소스를 체크
- Grafana 도입 / 리소스 체크를 시각화
> build: Grafana + Prometheus + nodeexporter를 통한 리소스 모니터링

- backend/games/consumers/GameConsumer.py
- backend/games/models.py
리팩토링을 하다가 pvp 닷지 수정을 해버렸다..
protocol 끊겼을 때의 예외를 처리하긴 했는데.. 테스트하니까 문제가 안 발생해서.. 작동하는 건진 모르겠다...
> fix: pvp 닷지 수정

- backend/games/consumers/GameConsumer.py
> Feat: 토너먼트 닷지 처리 #446

- backend/games/consumers/GameConsumer.py
- backend/games/serializers.py
> hotfix: 토너먼트 500 에러 수정

- frontend/src/pages/histories/one-on-one-page.js
- frontend/src/pages/histories/tournament-histories-details.js
- frontend/src/pages/histories/tournament-page.js
- frontend/src/utils/pagination.js
무엇을 합니다!
- 페이지네이션 버튼 클릭 이벤트 `onclick`에서 `click`으로 변경
- 페이지네이션 비활성화 시, `click` 이벤트 리스너에서 제거할 함수도 인자로 받게 함
- 이전, 다음 버튼 클릭 시 `dataset`이 아닌 `currentPage`를 기준으로 -1, +1을 함
- 페이지네이션 버튼을 클릭할 때마다 `currentPage`를 증가시키거나 감소시키는 이벤트도 같이 동작해야 하므로, 한 개의 이벤트 밖에 동작하지 않는 `onclick` 대신 `click` 사용
- `click` 이벤트에 등록된 모든 함수를 제거해버리면, `currentPage` 증감 함수도 같이 제거되어버리기 때문에 특정 함수만 제거할 수 있게 함
closes: #448
- e2e
> fix: 전적 페이지 페이지네이션 에러

- frontend/assets/css/histories.css
- frontend/src/pages/histories/one-on-one-histories-details.js
- frontend/src/utils/dateUtils.js
무엇을 합니다!
- casaul_1vs1 상세 페이지에서 승자 여부 아이콘으로 표시
- 날짜 포맷팅하는 함수 추가
- 닷지의 경우, 점수가 0:0일 때 승패가 명확하지 않음
closes: #459 
- e2e
> feat: 1vs1 모드 전적 상세 페이지에서 승자 표시

- frontend/src/pages/online-game/page.js
- frontend/src/pages/online-game/scoreBar.js
online-game 상단 scorebar 아바타 동적렌더링 했습니다.
closes: #476
> feat: online game 페이지 상단바 아바타 고정값인거 동적으로 바꿔주기

- backend/games/consumers/GameConsumer.py
- backend/src/choices.py
> Feat: 랭크 득점 추가 #467

- backend/games/consumers/GameConsumer.py
- backend/games/models.py
> Feat: 공 각도 조절

- frontend/src/pages/custom-game-list/page.js
무엇을 합니다!
- 네온 호버 구현
- 커서지정 할 떄 네온 호버가 있어야 방을 선택할 때 구분이 가능했다.
closes: #485
- 도커환경에서 네온 호버효과가 발생하는지 테스트
제 로컬 환경에서 방 리스트 간격, radius 정도 두가지 css가 살짝 이전과 달라보이는데 저는 딱히 건든게 없습니다.
머지 후에 한번 클러스터에서 확인해보는게 필요할거 같아요. 제 눈이 이상할 수도 있구요~
> refactor: 네온 호버 적용

- backend/login/views.py
- backend/src/settings.py
> Feat: jwt 토큰 분리 #495

- frontend/src/header/mainHeader/header.js
무엇을 합니다!
- mainheader에서 받은 인자들이 null이나 undefine인 경우 에러처리 되도록 수정
- mainheader에서 받은 인자들이 null이나 undefine인 경우 에러 발생
closes: #492
- 본인의 로컬 환경에서 해당 에러가 발생하는지 확인
우선 제 환경에서는 더 이상 에러가 나지 않는데, 그래도 클러스터 맥 환경에서 확인해보는게 좋을거 같습니다!
> fix : mainheader에서 받은 인자들이 null이나 undefine인 경우 에러처리

- backend/games/consumers/GameConsumer.py
> refactor: 게임 코드 리팩토링
